language: generic
sudo: required
services:
  - docker
jobs:
  include:
    - stage: test
      env: Type='virus scan'
      script:
      - ./include/travis/virus-scan.sh
    - stage: test
      env: Type='mock build test'
      script:
      - ./include/travis/run_in_centos7_docker.sh include/travis/mock_build_test.sh
    - stage: deploy-npm
      language: ruby
      rvm: 2.1
      if: branch =~ ^v\d+\.\d+\.\d+-1.*$
      env: Type='NPM Deploy'
      install:
        - . $HOME/.nvm/nvm.sh
        - nvm install 8
        - nvm use 8
        - npm install -g npm@latest
        - bundle install --jobs=3 --retry=3
      script: 
        - node --version
        - npm --version
        - npm run postversion
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        skip_cleanup: true
        api_key: "$NPM_TOKEN" 
    - stage: deploy-copr
      if: branch =~ ^v\d+\.\d+\.\d+-.+$
      env: Type='Copr deploy'
      before_deploy:
      - openssl aes-256-cbc -K $encrypted_253525cedcf6_key -iv $encrypted_253525cedcf6_iv -in include/copr-mfl.enc -out include/copr-mfl -d
      - curl -O https://raw.githubusercontent.com/m3t/travis_wait/master/travis_wait
      - chmod 755 travis_wait
      deploy:
        skip_cleanup: true
        provider: script
        script: ./travis_wait "./include/travis/run_in_centos7_docker.sh include/travis/copr-deploy.sh"
        on:
          all_branches: true


