language: generic
sudo: required
services:
  - docker
addons:
  apt:
    update: true
jobs:
  include:
    - stage: test
      name: "copr build test"
      script:
        - export SPEC=iml-online-help.spec
        - docker run -it -e SPEC="$SPEC" -e LOCAL_ONLY="True" -v $(pwd):/build:rw imlteam/copr
        - ((`find _topdir/RPMS -name *.rpm | wc -l` > 0))
    - stage: test
      name: "link check"
      language: node_js
      node_js:
        - "10"
      script:
        - npm run link-check
    - stage: deploy-npm
      name: "npm Deploy"
      language: ruby
      rvm: 2.1
      install:
        - . $HOME/.nvm/nvm.sh
        - nvm install 10
        - nvm use 10
        - npm install -g npm@latest
        - bundle install --jobs=3 --retry=3
      script:
        - node --version
        - npm --version
        - npm run postversion
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        skip_cleanup: true
        api_key: "$NPM_TOKEN"
        on:
          all_branches: true
    - stage: deploy-copr-r5.1
      name: "Copr deploy"
      script:
        - export OWNER=managerforlustre
        - export PROJECT=manager-for-lustre-5.1
        - export PACKAGE=iml-online-help
        - export SPEC=iml-online-help.spec
        - docker run -it -e OWNER="$OWNER" -e PROJECT="$PROJECT" -e PACKAGE="$PACKAGE" -e SPEC="$SPEC" -e PROD="True" -e KEY="$encrypted_253525cedcf6_key" -e IV="$encrypted_253525cedcf6_iv" -v $(pwd):/build:rw imlteam/copr
      on:
        all_branches: true
    - stage: cd
      name: "Continuous Deployment"
      script:
        - export OWNER=managerforlustre
        - export PROJECT=manager-for-lustre-devel
        - export PACKAGE=iml-online-help
        - export SPEC=iml-online-help.spec
        - docker run -it -e OWNER="$OWNER" -e PROJECT="$PROJECT" -e PACKAGE="$PACKAGE" -e SPEC="$SPEC" -e KEY="$encrypted_253525cedcf6_key" -e IV="$encrypted_253525cedcf6_iv" -v $(pwd):/build:rw imlteam/copr

stages:
  - test
  - name: deploy-npm
    if: branch =~ ^v\d+\.\d+\.\d+-1.*$
  - name: deploy-copr-r5.1
    if: branch =~ ^v\d+\.\d+\.\d+-.+-r5\.1$
  - name: cd
    if: branch = master AND type = push AND fork = false
