language: node_js
node_js:
- 6
cache: yarn
deploy:
  provider: npm
  email: joe.grund@intel.com
  api_key:
    secure: ctN4Udz6SHFl5R5cqpf02y5p9W7+57ypG4ZUek3zEgUif1nIAKgrbqFPwRLwEz7/jl555iBVIV0rrx5bL1DmDXOAG6t34L3fzl9HEUclGI1852TZjTZ1kK0bdIEah35ZzAKZAhG45218y7rdacZzF74gP2BzN1duxW8fhb0GBHZOVjGGfvpso0fs6J9TSskIKYASG3Hkl1j++T/AYIVGquwWjpcEYlwJUJwDnc6Erw1GU1BZkx7wtnTlok7rXum6T2MtcIGesNXEMi8QuHEeRn5ZEErsob9ICzB0TDl9GLgnPKOz/ORXThD7IPnLkEHFlyfJQqP/fSHrVOnt7miFvED7U8jGnVAWpLa5uo9Lh0EY6wjpLICSagg8X1OL5DllUCR8vikG9y8kMi/du6Rz7axgA+CCbcURfKiKuQNXbhvQXxv5f9eHNuQKuuZGV7BevxJeKOCBxKzWOiijFbcHMTegQfQX55F/HUlmrr5T3s/umpKaSMPNcoxRqgaRr5NUqM8sooycjbFgrgbNRHXnbVpFd2Wylta3p62WKRtKKoGWuTLpvYFZIRMrvaLcPiphLQd/Wo1yt7oPzOENYqFKCGhJNtvkrc7fKCcE67s9Zq5tmSvO2lSLs31SUGcpf6mnUvk37BR1g9k1EZF/7mAdVFKPZu1n6la7iiXG41VKAM4=
  on:
    tags: true
    repo: intel-hpdd/help-docs
