language: generic
sudo: required
services:
  - docker
addons:
  apt:
    update: true
jobs:
  include:
    - stage: test
      env: Type='mock build test'
      script:
      - ./include/travis/run_in_centos7_docker.sh include/travis/mock_build_test.sh
    - stage: cd
      git:
        depth: 999999
      env: 'Type=Continuous Deployment'
      script:
        - include/travis/copr-deploy.sh prepare
        - ./travis_wait "./include/travis/run_in_centos7_docker.sh include/travis/copr-deploy.sh build_srpm"
    - stage: deploy-npm
      env: Type='NPM Deploy'
      language: ruby
      rvm: 2.1
      install:
        - . $HOME/.nvm/nvm.sh
        - nvm install 8
        - nvm use 8
        - npm install -g npm@latest
        - bundle install --jobs=3 --retry=3
      script: 
        - node --version
        - npm --version
        - npm run postversion
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        skip_cleanup: true
        api_key: "$NPM_TOKEN"
        on:
          all_branches: true
    - stage: deploy-copr
      env: Type='Copr deploy'
      before_deploy:
      - include/travis/copr-deploy.sh prepare
      deploy:
        skip_cleanup: true
        provider: script
        script: ./travis_wait "./include/travis/run_in_centos7_docker.sh include/travis/copr-deploy.sh build"
        on:
          all_branches: true
stages:
  - test
  - name: cd
    if: branch = master AND type = push AND fork = false
  - name: deploy-npm
    if: branch =~ ^v\d+\.\d+\.\d+$
  - name: deploy-copr
    if: branch =~ ^v\d+\.\d+\.\d+-.+$
