theme: jekyll-theme-cayman
exclude:
  [
    vendor,
    include,
    node_modules,
    package.json,
    package-lock.json,
    iml-online-help.spec,
    Makefile,
    LICENSE,
    Gemfile,
    Gemfile.lock,
    travis_env,
  ]
version: "5.0.0.0"
package_name: "iml-5.0.0.0"
lustre_version: "2.10.7"
lustre_package_name: "lustre-2.10.7"
lustre_kernel_version: "3.10.0-957.1.3.el7"
e2fsprogs_version: "1.44.5"
centos_version: "7.6"
repository: "whamcloud/Online-Help"
